### ISSUE TITLE
[wifi_easy_connect] Checklist for 1.0

### ISSUE THREAD

**Issue by daadu** [flutternetwork/WiFiFlutter#252]
## APIs
- `Future<WiFiEasyConnectCapability> hasCapability()`
- `Future<EnrollErrors?> `

### Platform Feature Coverage
- [ ] Android (`android.net.wifi.rtt` package)
 - constants
   - [ ] `Settings.ACTION_PROCESS_WIFI_EASY_CONNECT_URI`
   - [ ] `Settings.EXTRA_EASY_CONNECT_ATTEMPTED_SSID`
   - [ ] `Settings.EXTRA_EASY_CONNECT_BAND_LIST`
   - [ ] `Settings.EXTRA_EASY_CONNECT_CHANNEL_LIST`
   - [ ] `Settings.EXTRA_EASY_CONNECT_ERROR_CODE`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_AUTHENTICATION`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_BUSY`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_CANNOT_FIND_NETWORK`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_CONFIGURATION`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_ENROLLEE_AUTHENTICATION`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_ENROLLEE_FAILED_TO_SCAN_NETWORK_CHANNEL`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_ENROLLEE_REJECTED_CONFIGURATION`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_GENERIC`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_INVALID_NETWORK`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_INVALID_URI`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_NOT_COMPATIBLE`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_NOT_SUPPORTED`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_TIMEOUT`
   - [ ] `EasyConnectStatusCallback.EASY_CONNECT_EVENT_FAILURE_URI_GENERATION`
 - methods
   - [ ] `WifiManager.isEasyConnectSupported()`
   - [ ] `WifiManager.isEasyConnectEnrolleeResponderModeSupported()`
  

## Documentation
- [ ] document API references
- [ ] proper README

## Test
- [ ] automated unit tests
  - [ ] dart code
  - [ ] android code
  - [ ] ios code
- [ ]  automated integration tests
