### ISSUE TITLE
[wifi_passpoint] Checklist for 1.0

### ISSUE THREAD

**Issue by daadu** [flutternetwork/WiFiFlutter#290]
## APIs
- ??

### Platform Feature Coverage
- [ ] Android
 - constants
   ??
 - methods
   ??
- [ ] iOS
  - [ ] Entitlements
    - [ ] `com.apple.developer.networking.HotspotConfiguration` [Hotspot Configuration]
  - [ ] `NEHotspotConfigurationManager ` 
    - [ ] `class var shared: NEHotspotConfigurationManager { get }`
    - [ ] `func apply(_ configuration: NEHotspotConfiguration, completionHandler: ((Error?) -> Void)? = nil)`
  - [ ] `NEHotspotConfiguration`
    - [ ] `init(hs20Settings: NEHotspotHS20Settings, eapSettings: NEHotspotEAPSettings)`
    - [ ] `@NSCopying var lifeTimeInDays: NSNumber { get set }`
    - [ ] `var joinOnce: Bool { get set }`
    - [ ] `var hidden: Bool { get set }`
  - [ ] `NEHotspotHS20Settings `
    - [ ] `init(domainName: String, roamingEnabled: Bool)`
    - [ ] `var domainName: String { get }`
    - [ ] `var isRoamingEnabled: Bool { get set }`
    - [ ] `var mccAndMNCs: [String] { get set }`
    - [ ] `var naiRealmNames: [String] { get set }`
    - [ ] `var roamingConsortiumOIs: [String] { get set }`
  

## Documentation
- [ ] document API references
- [ ] proper README

## Test
- [ ] automated unit tests
  - [ ] dart code
  - [ ] android code
  - [ ] ios code
- [ ]  automated integration tests
